global.CONFIG = {
  API_HOST: process.env.API_HOST,
  FRONTEND_HOST: process.env.FRONTEND_HOST,
  SENTRY_PUBLIC_DSN: process.env.SENTRY_PUBLIC_DSN,
  SENTRY_PRIVATE_DSN: process.env.SENTRY_PRIVATE_DSN
}
